server:
  servlet:
    context-path: /library-app

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    oauth:
      clientId: swagger-ui
      clientSecret: swagger-ui-secret
      useBasicAuthenticationWithAccessCodeGrant: true
  api-docs:
    path: /v3/api-docs
  swagger-ui-config:
    url: /v3/api-docs/swagger-config


secret:
  key: e246d2122b6c12acc7ccd5d685a1eab6899790bb26bd20cc7782621480a20d48


